-- llm_usage table schema — generated by /llm-integration
-- Run this migration ONCE in your database

CREATE TABLE IF NOT EXISTS llm_usage (
  id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- Request identification
  request_id         TEXT NOT NULL DEFAULT gen_random_uuid()::text,
  session_id         TEXT,
  user_id            UUID,             -- FK to your users table (optional)
  feature            TEXT NOT NULL,    -- 'chatbot' | 'rag' | 'search' | custom

  -- Provider and model
  provider           TEXT NOT NULL CHECK (provider IN ('anthropic', 'openai', 'google')),
  model              TEXT NOT NULL,

  -- Token counts (raw — recalculate cost if pricing changes)
  input_tokens       INTEGER NOT NULL DEFAULT 0,
  output_tokens      INTEGER NOT NULL DEFAULT 0,
  cache_write_tokens INTEGER NOT NULL DEFAULT 0,  -- Anthropic: cache_creation_input_tokens
  cache_read_tokens  INTEGER NOT NULL DEFAULT 0,  -- Anthropic: cache_read_input_tokens / OpenAI: cached_tokens

  -- Cost (calculated at insert time — use raw tokens to recalculate if needed)
  cost_usd           NUMERIC(12, 8) NOT NULL DEFAULT 0,

  -- Performance metrics
  latency_ms         INTEGER NOT NULL,
  ttft_ms            INTEGER,          -- Time to first token (streaming only)

  -- NO PII columns: no prompt_text, response_text, user_ip, user_email
  -- Store only metrics, never conversation content

  -- Extensible metadata (for future fields without migrations)
  metadata           JSONB DEFAULT '{}'::jsonb
);

-- Indexes for common query patterns
CREATE INDEX IF NOT EXISTS idx_llm_usage_user_created ON llm_usage(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_llm_usage_feature      ON llm_usage(feature, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_llm_usage_session      ON llm_usage(session_id);

-- Row-Level Security (RLS) — enable if using Supabase or PostgreSQL RLS
-- ALTER TABLE llm_usage ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY llm_usage_user_policy ON llm_usage
--   USING (user_id = auth.uid());
